version: '3.7'
services:
  web:
    container_name: web-service
    build:
      context: .
      dockerfile: Dockerfile
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", "-jar", "/app.jar"]
    volumes:
      - ./database.mv.db:/data/database.mv.db
      - ./database.trace.db:/data/database.trace.db
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - back-network
    external_links:
      - rabbitmq
    restart: always

  rabbitmq:
    container_name: web-rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  back-network:
    external: true
